version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - vnet
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s
  backend:
    container_name: backend
    image: node:18.15.0
    tty: true
    working_dir: /home/node/app
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    volumes:
      - ./backend:/home/node/app
    networks:
      - vnet
    depends_on:
      - mysql
    command: /bin/bash -c "usermod -u `stat -c '${UID}' .` node && groupmod -g `stat -c '${GID}' .` node && su node -c 'npm install && npm run dev'"
  # frontend:
  #   container_name: frontend
  #   image: node:18.15.0
  #   tty: true
  #   working_dir: /home/node/app
  #   ports:
  #     - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT
  #   volumes:
  #     - ./frontend:/home/node/app
  #   networks:
  #     - vnet
  #   depends_on:
  #     - backend
  #   command: /bin/bash -c "usermod -u `stat -c '${UID}' .` node && groupmod -g `stat -c '${GID}' .` node && su node -c 'npm install && npm run dev'"

networks:
  vnet:
