"use client"

import { SessionProvider } from "next-auth/react";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Link from 'next/link'
import './globals.css'
import { Header } from "./components/header";

export const metadata = {
  title: 'Título',
  description: 'Generated by create next app'
}

const links = [{
  label: "Home",
  route: "/",
}, {
  label: "Books",
  route: "/books",
}]

export default function RootLayout({ children, session }) {

  return (
    <html lang='en'>
      <body>
        <SessionProvider session={session}>
          <ToastContainer />
          <Header links={links} />
          {children}
        </SessionProvider>
      </body>
    </html >
  )
}
